version: '3.7'
services:
  kratos-migrate:
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    volumes:
      - "./var/lib/kratos-sqlite:/var/lib/sqlite"
      - "./etc/config/kratos:/etc/config/kratos"

  kratos:
    depends_on:
      kratos-migrate:
        condition: service_completed_successfully
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - "./ver/lib/kratos-sqlite:/var/lib/sqlite"
      - "./etc/config/kratos:/etc/config/kratos"

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.2.0
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - COOKIE_SECRET=changeme123
      - CSRF_COOKIE_NAME=x-csrf-token
      - CSRF_COOKIE_SECRET=changeme123
      - DANGEROUSLY_DISABLE_SECURE_CSRF_COOKIES=true
    depends_on:
      kratos:
        condition: service_started

  mailslurper:
    image: oryd/mailslurper:latest-smtps

  hydra-migrate:
    image: oryd/hydra:v2.2
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - "./var/lib/hydra-sqlite:/var/lib/sqlite"
      - "./etc/config/hydra:/etc/config/hydra"

  hydra:
    image: oryd/hydra:v2.2
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: serve -c /etc/config/hydra/hydra.yml all --dev
    volumes:
      - "./var/lib/hydra-sqlite:/var/lib/sqlite"
      - "./etc/config/hydra:/etc/config/hydra"
    depends_on:
      hydra-migrate:
        condition: service_completed_successfully

  keto:
    image: oryd/keto:v0.12
    command: serve -c /etc/config/keto.yml
    volumes:
      - type: bind
        source: ./etc/config/keto/keto.yml
        target: /etc/config/keto.yml

  oathkeeper:
    image: oryd/oathkeeper:v0.40
    command: serve --config=/etc/config/oathkeeper/config.yml
    environment:
      - TRACING_PROVIDER=jaeger
      - TRACING_PROVIDERS_JAEGER_PROPAGATION=jaeger
      - TRACING_PROVIDERS_JAEGER_SAMPLING_SERVER_URL=http://ory-jaeger-1:5778/sampling
      - TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=ory-jaeger-1:6831
      - TRACING_PROVIDERS_JAEGER_SAMPLING_TYPE=const
      - TRACING_PROVIDERS_JAEGER_SAMPLING_VALUE=1
    volumes:
      - type: bind
        source: ./etc/config/oathkeeper
        target: /etc/config/oathkeeper

  jaeger:
    image: jaegertracing/all-in-one

networks:
  ory:
    external: true